"use client";
import { CircleDollarSign, ExternalLink, Pencil } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { ChargeStatusBadge } from "./charge-status-badge";
import { PaymentDialog } from "@/components/payments/payment-dialog";
import { formatMoney } from "@/lib/domain/money";
import type { ChargeListItem } from "@/lib/queries/charges";
export function ChargeTable({ charges, today, createHref = "/charges/new" }: { charges: ChargeListItem[]; today: string; createHref?: string }) {
  const [paying, setPaying] = useState<ChargeListItem | null>(null);
  if (!charges.length) return <section className="charge-empty"><CircleDollarSign size={24} aria-hidden="true" /><div><h2>No hay cobros para esta vista</h2><p>Cambiá los filtros o creá una obligación manual.</p></div><Link className="primary-button" href={createHref}>Nuevo cobro</Link></section>;
  return <><section className="charge-ledger"><div className="charge-table-wrap"><table className="charge-table"><thead><tr><th>Cliente / concepto</th><th>Vencimiento</th><th>Estado</th><th className="align-end">Importe</th><th className="align-end">Saldo</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{charges.map((charge) => { const balance = Math.max(charge.amountMinor - charge.amountPaidMinor, 0); const editable = !charge.generatedAutomatically && charge.persistedStatus === "pending" && charge.amountPaidMinor === 0; return <tr key={charge.id}><td><strong>{charge.clientName}</strong><small>{charge.description}{charge.serviceName ? ` · ${charge.serviceName}` : ""}</small></td><td><time dateTime={charge.dueDate}>{charge.dueDate.split("-").reverse().join("/")}</time></td><td><ChargeStatusBadge status={charge.status} /></td><td className="align-end money-data">{formatMoney(charge.amountMinor, charge.currency)}</td><td className="align-end money-data">{formatMoney(balance, charge.currency)}</td><td className="charge-actions">{!["paid", "cancelled"].includes(charge.status) ? <button className="primary-button primary-button--compact" type="button" onClick={() => setPaying(charge)}>Cobrar</button> : null}{editable ? <Link className="icon-button" href={`/charges/${charge.id}/edit`} aria-label={`Editar cobro ${charge.description}`}><Pencil size={15} /></Link> : null}<Link className="icon-button" href={`/charges/${charge.id}`} aria-label={`Abrir historial de ${charge.description}`}><ExternalLink size={15} /></Link></td></tr>; })}</tbody></table></div><div className="charge-card-list">{charges.map((charge) => { const balance = Math.max(charge.amountMinor - charge.amountPaidMinor, 0); const editable = !charge.generatedAutomatically && charge.persistedStatus === "pending" && charge.amountPaidMinor === 0; return <article className="charge-card" key={charge.id}><header><div><strong>{charge.clientName}</strong><span>{charge.description}</span></div><ChargeStatusBadge status={charge.status} /></header><dl><div><dt>Saldo</dt><dd>{formatMoney(balance, charge.currency)}</dd></div><div><dt>Vence</dt><dd>{charge.dueDate.split("-").reverse().join("/")}</dd></div></dl><footer>{!["paid", "cancelled"].includes(charge.status) ? <button className="primary-button" type="button" onClick={() => setPaying(charge)}>Registrar pago</button> : null}{editable ? <Link className="secondary-button" href={`/charges/${charge.id}/edit`} aria-label={`Editar cobro ${charge.description}`}>Editar</Link> : null}<Link className="secondary-button" href={`/charges/${charge.id}`}>Ver historial</Link></footer></article>; })}</div></section>{paying ? <PaymentDialog charge={paying} today={today} open onClose={() => setPaying(null)} /> : null}</>;
}
