import { Plus, Search } from "lucide-react";
import Link from "next/link";
import { ChargeTable } from "@/components/charges/charge-table";
import { LedgerSelect } from "@/components/ui/ledger-select";
import { todayInBusinessZone } from "@/lib/domain/commercial-date";
import { getCharges } from "@/lib/queries/charges";

const filters = [{ value: "all", label: "Todos" }, { value: "current_month", label: "Este mes" }, { value: "upcoming", label: "Próximos" }, { value: "due_today", label: "Vencen hoy" }, { value: "overdue", label: "Vencidos" }, { value: "partial", label: "Parciales" }, { value: "paid", label: "Cobrados" }] as const;
export default async function ChargesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams; const today = todayInBusinessZone(new Date()); const status = filters.some((item) => item.value === params.status) ? params.status! : "all";
  const items = await getCharges({ status, search: params.q, currency: params.currency, clientId: params.clientId, serviceId: params.serviceId, from: params.from, to: params.to }, today);
  return <main className="charges-page"><header className="page-heading page-heading--actions"><div><p className="eyebrow">Libro de cuentas por cobrar</p><h1>Cobros</h1><p>Encontrá lo urgente y registrá el movimiento sin perder el hilo.</p></div><Link className="primary-button" href="/charges/new"><Plus size={17} /> Nuevo cobro</Link></header>
    <section className="charge-toolbar" aria-label="Buscar y filtrar cobros"><form className="client-search" role="search"><Search size={17} /><label className="sr-only" htmlFor="charge-search">Buscar cobros</label><input id="charge-search" name="q" type="search" defaultValue={params.q ?? ""} placeholder="Cliente o concepto" /><input type="hidden" name="status" value={status} /><input type="hidden" name="currency" value={params.currency ?? ""} /><input type="hidden" name="from" value={params.from ?? ""} /><input type="hidden" name="to" value={params.to ?? ""} /><button className="quiet-button">Buscar</button></form><nav className="filter-tabs" aria-label="Filtrar cobros">{filters.map((filter) => { const query = new URLSearchParams(); if (params.q) query.set("q", params.q); if (params.currency) query.set("currency", params.currency); if (params.from) query.set("from", params.from); if (params.to) query.set("to", params.to); if (filter.value !== "all") query.set("status", filter.value); return <Link key={filter.value} href={query.size ? `/charges?${query}` : "/charges"} aria-current={status === filter.value ? "page" : undefined}>{filter.label}</Link>; })}</nav><details className="charge-advanced"><summary>Moneda y período</summary><form><input type="hidden" name="q" value={params.q ?? ""} /><input type="hidden" name="status" value={status} /><label><span>Moneda</span><LedgerSelect name="currency" label="Moneda del filtro" defaultValue={params.currency ?? ""} options={[{ value: "", label: "Todas" }, { value: "USD", label: "USD" }, { value: "ARS", label: "ARS" }]} /></label><label><span>Desde</span><input className="form-control" name="from" inputMode="numeric" placeholder="AAAA-MM-DD" defaultValue={params.from ?? ""} /></label><label><span>Hasta</span><input className="form-control" name="to" inputMode="numeric" placeholder="AAAA-MM-DD" defaultValue={params.to ?? ""} /></label><button className="secondary-button">Aplicar filtros</button></form></details></section>
    <div className="client-result-count" aria-live="polite">{items.length} {items.length === 1 ? "cobro" : "cobros"}</div><ChargeTable charges={items} today={today} /></main>;
}
